version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx/
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - debbie
    networks:
      - backend
  php-fpm:
    build:
      args:
        user: foo
        uid: 1000
      context: ./docker/php-fpm/
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: example
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
